CREATE DATABASE BitOrchestraDB

USE BitOrchestraDB

CREATE TABLE UserInfo(
UserId INT PRIMARY KEY IDENTITY NOT NULL,
UserName VARCHAR(MAX) NOT NULL,
DateOfBirth DATE NOT NULL,
Married BIT NOT NULL, --BIT in sql = bool
Phone VARCHAR(MAX) NOT NULL,
Salary DECIMAL(18,2) NOT NULL
)

INSERT INTO UserInfo
VALUES(
'User3', '2025-10-22', 0, '+380973455647', 12.7
)